/**
 * Screenshots of the opening screen and the task wizards (ADR-034) at 360,
 * 390 and 1440 px: the opening screen, the search with results, the search
 * with a task that is not built yet, the search with nothing found, every
 * wizard's steps and the saved state. Screenshots of the running app, not
 * mockups; written to docs/ux/2026-10-03-home/shots/.
 *
 * Usage: npm run build && npx next start -p 3100   (in another shell)
 *        node scripts/home-shots.mjs               (SHOT_URL to point elsewhere)
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';

import { installSavePicker } from './lib/kesit-flow.mjs';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(root, '..', 'docs', 'ux', '2026-10-03-home', 'shots');
const sample = join(root, 'tests', 'media', 'sample-24s.mp4');
const music = join(root, 'tests', 'media', 'tone-30s.m4a');
const baseURL = process.env.SHOT_URL ?? 'http://127.0.0.1:3100';
/** `--only=home,kucult,ses,sustur`: only those shots (the rest are left as they are). */
const only = (process.argv.find((a) => a.startsWith('--only=')) ?? '--only=').slice(7).split(',').filter(Boolean);

mkdirSync(outDir, { recursive: true });

/** A talk with pauses (generated tone bursts): something for "Boşlukları at" to find. */
function pausesVideo() {
  const dir = join(root, 'tests', 'media', 'silence');
  const file = join(dir, 'shots-pauses.mp4');
  if (existsSync(file)) return file;
  mkdirSync(dir, { recursive: true });
  const speech = 'lt(t,1.6)+gte(t,2.6)*lt(t,4.1)+gte(t,4.4)*lt(t,6)+gte(t,6.5)*lt(t,7.8)+gte(t,9.3)*lt(t,12)';
  execFileSync(
    'ffmpeg',
    [
      '-hide_banner', '-loglevel', 'error', '-y',
      '-f', 'lavfi', '-i', 'testsrc2=s=1280x720:r=30:d=12',
      '-f', 'lavfi', '-i', `aevalsrc=exprs=0.25*sin(2*PI*440*t)*(${speech}):s=48000:d=12`.replace(/,/g, '\\,'),
      '-c:v', 'libx264', '-preset', 'veryfast', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest', '-movflags', '+faststart',
      file,
    ],
    { stdio: 'pipe' },
  );
  return file;
}

/**
 * A dark, camera-like picture for "İyileştir" (ADR-037), in a folder of its own (the e2e fixtures
 * are generated by their own recipe and must stay byte-identical): the same kind of scene as the e2e
 * fixture `karanlik.mp4` (tests/e2e/enhance-media.ts) — fractal noise over colour gradients,
 * about two stops underexposed. Not real footage.
 */
function darkVideo() {
  const dir = join(root, 'tests', 'media', 'enhance', 'shots');
  const file = join(dir, 'karanlik.mp4');
  if (existsSync(file)) return file;
  mkdirSync(dir, { recursive: true });
  execFileSync(
    'ffmpeg',
    [
      '-hide_banner', '-loglevel', 'error', '-y',
      '-f', 'lavfi', '-i', 'perlin=s=1280x720:r=30:octaves=6:persistence=0.65:xscale=6:yscale=6:tscale=0.4:random_mode=seed:random_seed=7',
      '-f', 'lavfi', '-i', 'gradients=s=1280x720:r=30:c0=0x5a6f8f:c1=0xc9b89a:c2=0x6f8f6a:c3=0x9a7070:n=4:speed=0.01:seed=3',
      '-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=48000:duration=3',
      '-filter_complex',
      '[0:v]format=gbrp[n];[1:v]format=gbrp[g];[n][g]blend=all_mode=overlay,eq=contrast=1.3,' +
        'drawgrid=w=320:h=240:t=3:c=white@0.55,drawbox=x=120:y=100:w=180:h=120:c=black@0.75:t=fill,' +
        'drawbox=x=840:y=420:w=240:h=160:c=white@0.8:t=fill,noise=alls=4:allf=t,' +
        "lutrgb=r='val*0.5':g='val*0.5':b='val*0.5',scale=out_color_matrix=bt709:out_range=tv,format=yuv420p[v]",
      '-map', '[v]', '-map', '2:a', '-t', '3',
      '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '14', '-pix_fmt', 'yuv420p', '-g', '30',
      '-colorspace', 'bt709', '-color_primaries', 'bt709', '-color_trc', 'bt709', '-color_range', 'tv',
      '-c:a', 'aac', '-b:a', '128k', '-shortest', file,
    ],
    { stdio: 'pipe' },
  );
  return file;
}

const SIZES = [
  { name: '360', width: 360, height: 780, phone: true },
  { name: '390', width: 390, height: 844, phone: true },
  { name: '1440', width: 1440, height: 900, phone: false },
];

const browser = await chromium.launch({ args: ['--autoplay-policy=no-user-gesture-required'] });

for (const size of SIZES) {
  const context = await browser.newContext({
    viewport: { width: size.width, height: size.height },
    deviceScaleFactor: 1,
    hasTouch: size.phone,
    isMobile: size.phone,
    reducedMotion: 'reduce',
  });
  const page = await context.newPage();
  await installSavePicker(page, { plainNames: true });
  const shot = async (name) => {
    await page.waitForTimeout(250);
    await page.screenshot({ path: join(outDir, `${name}-${size.name}.png`), fullPage: true });
    console.log(`${name}-${size.name}.png`);
  };
  const open = async (path) => {
    await page.goto(`${baseURL}${path}`);
    await page.waitForLoadState('networkidle');
  };
  const pick = async (file) => {
    await page.getByTestId('video-input').setInputFiles(file);
  };
  const saved = async () => {
    await page.getByTestId('wizard-download').click();
    await page.getByTestId('download-saved').waitFor({ timeout: 180_000 });
  };

  // ---- the opening screen and the search (`--only=home`)
  if (only.length === 0 || only.includes('home')) {
    await open('/');
    await shot('01-home');
    await page.getByTestId('finder-input').fill('tiktok için dikey');
    await shot('02-search-results');
    await page.getByTestId('finder-input').fill('sesi kes');
    await shot('03-search-two-results');
    // A request the app cannot serve yet: "Bunu henüz yapamıyoruz.", no button.
    await page.getByTestId('finder-input').fill('gife çevir');
    await shot('04-search-unavailable');
    await page.getByTestId('finder-input').fill('pizza siparişi');
    await shot('05-search-none');
  }

  if (only.length === 0) {
  // ---- Kes: pick → the editor, first-run hint showing
  await open('/yap/kes');
  await shot('10-kes-1-pick');
  await pick(sample);
  await page.getByTestId('preview-video').waitFor();
  await shot('11-kes-2-editor');

  // ---- Boşlukları at
  await open('/yap/bosluk');
  await pick(pausesVideo());
  await page.getByTestId('bosluk-summary').waitFor({ timeout: 60_000 });
  await shot('20-bosluk-2-choice');
  await saved();
  await shot('21-bosluk-3-saved');

  // ---- Dikey yap
  await open('/yap/dikey');
  await shot('30-dikey-1-pick');
  await pick(sample);
  await page.getByTestId('dikey-choice').waitFor();
  await shot('31-dikey-2-fill');
  await page.getByTestId('option-contain').check();
  await shot('32-dikey-2-fit');
  await page.getByTestId('wizard-download').click();
  await page.getByTestId('download-running').waitFor({ timeout: 60_000 }).catch(() => undefined);
  await shot('33-dikey-3-running');
  await page.getByTestId('download-saved').waitFor({ timeout: 180_000 });
  await shot('34-dikey-3-saved');

  // ---- Müzik ekle
  await open('/yap/muzik');
  await pick(sample);
  await page.getByTestId('muzik-pick').waitFor();
  await shot('40-muzik-2-no-music');
  await page.getByTestId('audio-input').setInputFiles(music);
  await page.getByTestId('muzik-picked').waitFor();
  await shot('41-muzik-2-choice');
  await saved();
  await shot('42-muzik-3-saved');

  // ---- Her yerde açılsın
  await open('/yap/cevir');
  await pick(sample);
  await page.getByTestId('cevir-info').waitFor();
  await page.getByTestId('cevir-already').waitFor({ timeout: 30_000 }).catch(() => undefined);
  await shot('50-cevir-2-info');
  await saved();
  await shot('51-cevir-3-saved');

  }

  // ---- Küçült (ADR-035): the choice with what each size would give, then the real size
  if (only.length === 0 || only.includes('kucult')) {
    await open('/yap/kucult');
    await pick(sample);
    await page.locator('[data-testid="size-hint-whatsapp"]:not([data-state="pending"])').waitFor({ timeout: 60_000 });
    await shot('60-kucult-2-choice');
    await page.getByTestId('option-whatsapp').check();
    await saved();
    await shot('61-kucult-3-saved');
  }

  // ---- Sesini al (ADR-035)
  if (only.length === 0 || only.includes('ses')) {
    await open('/yap/ses');
    await pick(sample);
    await page.getByTestId('ses-info').waitFor();
    await shot('70-ses-2-info');
    await saved();
    await shot('71-ses-3-saved');
  }

  // ---- Sesi kapat (7 Oct 2026): found by typing, the one-line step, the saved result
  if (only.length === 0 || only.includes('sustur')) {
    await open('/');
    await page.getByTestId('finder-input').fill('sesini kapat');
    await shot('75-sesi-kapat-0-search');
    await open('/yap/sustur');
    await shot('75-sesi-kapat-1-pick');
    await pick(sample);
    await page.getByTestId('sustur-info').waitFor();
    await shot('75-sesi-kapat-2-info');
    await saved();
    await shot('75-sesi-kapat-3-saved');
  }

  // ---- Yazıya dök (ADR-036): the real model on a real sentence (tests/media/SPEECH_SOURCE.md).
  // Needs the model files next to the site: node scripts/fetch-models.mjs --dest=public/models
  if (only.length === 0 || only.includes('yazi')) {
    const speech = join(root, 'tests', 'media', 'speech-fleurs-en-01.mp4');
    await open('/yap/yazi');
    await pick(speech);
    await page.getByTestId('model-download').waitFor({ timeout: 60_000 });
    // With a graphics card the large model is offered and pre-selected; the pictures are of the small one.
    if (await page.getByTestId('option-model-base').count()) await page.getByTestId('option-model-base').check();
    await page.getByTestId('model-download').waitFor({ timeout: 60_000 });
    await shot('80-yazi-2-model');
    await page.getByTestId('model-download').click();
    await page.getByTestId('transcribe-start').waitFor({ timeout: 600_000 });
    await shot('81-yazi-2-ready');
    await page.getByTestId('transcribe-start').click();
    await page.locator('[data-testid="transcribe-running"][data-phase="writing"]').waitFor({ timeout: 120_000 }).catch(() => undefined);
    await shot('82-yazi-2-running');
    await page.getByTestId('transcript-panel').waitFor({ timeout: 600_000 });
    await page.getByTestId('transcript-row').nth(1).getByTestId('transcript-line').click();
    await shot('83-yazi-2-result');
    await page.getByTestId('transcript-row').first().getByTestId('transcript-edit').click();
    await shot('84-yazi-2-correcting');
    await page.getByTestId('transcript-cancel').click();
    await saved();
    await shot('85-yazi-3-saved');
    await page.getByTestId('wizard-open-editor').click();
    await page.getByTestId('preview-video').waitFor({ timeout: 60_000 });
    await page.getByTestId('transcript-row').nth(1).getByTestId('transcript-check').click();
    await page.getByTestId('transcript-row').nth(2).getByTestId('transcript-check').click();
    await shot('86-yazi-editor-panel');
    await page.getByTestId('transcript-make-kesit').click();
    await page.getByTestId('side-tab-kesit').click();
    await shot('87-yazi-editor-kesit-from-text');
  }

  // ---- İyileştir (ADR-037): the card, the honest search result, before/after, the three strengths,
  // a video with nothing to fix, saved, and the same setting in the editor.
  if (only.length === 0 || only.includes('iyilestir')) {
    const ready = () => page.locator('[data-testid="enhance-preview"][data-status="ready"]').waitFor({ timeout: 120_000 });
    await open('/');
    await page.getByTestId('task-iyilestir').waitFor();
    await shot('90-iyilestir-0-home');
    await page.getByTestId('finder-input').fill('4K yap');
    await page.getByTestId('result-iyilestir').waitFor();
    await shot('91-iyilestir-0-search-honest');
    await open('/yap/iyilestir');
    await pick(darkVideo());
    await ready();
    await page.getByTestId('iyilestir-summary').waitFor();
    await shot('92-iyilestir-2-choice');
    await page.getByTestId('option-strong').check();
    await ready();
    await page.getByTestId('enhance-slider').fill('30');
    await shot('93-iyilestir-2-strong');
    await page.getByTestId('option-auto').check();
    await ready();
    await saved();
    await shot('94-iyilestir-3-saved');
    await page.getByTestId('wizard-open-editor').click();
    await page.getByTestId('preview-video').waitFor({ timeout: 60_000 });
    await page.getByTestId('open-settings').click();
    await page.getByTestId('inspector-tab-frame').click();
    await ready();
    await page.getByTestId('enhance-setting').scrollIntoViewIfNeeded();
    await shot('95-iyilestir-editor-setting');
    // A test card: flat graphics, nothing to fix, and the wizard says so.
    await open('/yap/iyilestir');
    await pick(sample);
    await ready();
    await page.getByTestId('wizard-blocked').waitFor();
    await shot('96-iyilestir-2-nothing');
  }

  await context.close();
}

await browser.close();
