import { mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test, type Page } from '@playwright/test';

import { ffmpegEnvelope, silenceFixture, type FixtureName } from './silence-media';

/**
 * Silence-cut suggestions (ADR-018). The media is generated by ffmpeg with
 * known gaps (see silence-media.ts), so the expected cuts are exact:
 * bursts.mp4 has a 1.2 s gap at 1.0–2.2 s and a 0.3 s gap at 3.2–3.5 s; with
 * the default 0.7 s minimum and 150 ms margin, only 1.150–2.050 s is suggested.
 */

const S = 1_000_000;
const TOLERANCE_US = 20_000;
const SHOTS = join(process.cwd(), 'screenshots');

async function openWith(page: Page, name: FixtureName) {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const { file } = silenceFixture(name);
  await page.goto('/editor');
  await expect(page.getByTestId('open-export')).toBeVisible();
  await page.getByTestId('video-input').setInputFiles(file);
  await expect(page.getByTestId('preview-video')).toBeVisible();
  return errors;
}

async function addMoment(page: Page, start: string, end: string) {
  await page.getByTestId('range-start').fill(start);
  await page.getByTestId('range-end').fill(end);
  await page.getByTestId('add-moment').click();
}

function dialog(page: Page) {
  return page.getByRole('dialog', { name: 'Sessizlikleri bul' });
}

/** Opens the dialog and waits for the analysis to finish. */
async function findSilences(page: Page) {
  await page.getByTestId('open-silence').click();
  await expect(dialog(page)).toBeVisible();
  await expect(page.getByTestId('silence-running')).toHaveCount(0, { timeout: 30_000 });
  await expect(page.getByTestId('silence-clips')).toBeVisible();
}

async function suggestionRanges(page: Page): Promise<Array<{ startUs: number; endUs: number }>> {
  const rows = page.getByTestId('silence-suggestion');
  const count = await rows.count();
  const ranges: Array<{ startUs: number; endUs: number }> = [];
  for (let index = 0; index < count; index += 1) {
    const row = rows.nth(index);
    ranges.push({
      startUs: Number(await row.getAttribute('data-start-us')),
      endUs: Number(await row.getAttribute('data-end-us')),
    });
  }
  return ranges;
}

function expectNear(actualUs: number, expectedUs: number) {
  expect(Math.abs(actualUs - expectedUs)).toBeLessThanOrEqual(TOLERANCE_US);
}

test.describe('silence suggestions', () => {
  test('the button explains why it is unavailable until there is a moment', async ({ page }) => {
    await page.goto('/editor');
    const button = page.getByTestId('open-silence');
    await expect(button).toHaveAttribute('aria-disabled', 'true');
    await expect(page.getByTestId('silence-open-hint')).toHaveText(
      'Önce bir an ekle; sessizlikler anların içinde aranır.',
    );
    // Playwright will not click an aria-disabled button; a keyboard press can.
    await button.focus();
    await page.keyboard.press('Enter');
    await expect(dialog(page)).toHaveCount(0);
  });

  for (const name of ['bursts', 'noisy'] as const) {
    test(`suggests exactly the long gap (${name}), toggles, re-tunes, applies as one undo step`, async ({
      page,
    }) => {
      const errors = await openWith(page, name);
      await addMoment(page, '00:00.000', '00:04.500');
      await expect(page.getByTestId('moment-count')).toHaveText('1 an');
      await findSilences(page);

      // Exactly one suggestion: the 1.2 s gap minus 150 ms on each side.
      const ranges = await suggestionRanges(page);
      expect(ranges).toHaveLength(1);
      const [only] = ranges;
      expectNear(only!.startUs, 1.15 * S);
      expectNear(only!.endUs, 2.05 * S);
      await expect(page.getByTestId('silence-status')).toHaveText('1 öneri bulundu, 1 tanesi seçili.');

      // Checked by default; the summary is what Apply will do.
      const check = page.getByTestId('silence-check');
      await expect(check).toBeChecked();
      await expect(page.getByTestId('silence-summary-moments')).toHaveText('1 → 2');
      await expect(page.getByTestId('silence-summary-duration')).toHaveText(/^00:04\.500 → 00:03\.(5[89]\d|6[0-4]\d)$/);

      // Toggle off: nothing to apply. Toggle on again.
      await check.uncheck();
      await expect(page.getByTestId('silence-summary-nothing')).toBeVisible();
      await expect(page.getByTestId('silence-apply')).toBeDisabled();
      await check.check();
      await expect(page.getByTestId('silence-apply')).toBeEnabled();

      // A longer minimum pause (1.5 s) makes the 1.2 s gap disappear at once
      // (cached envelope, no new analysis); defaults bring it back.
      const min = page.getByTestId('silence-min');
      await min.focus();
      for (let step = 0; step < 8; step += 1) await page.keyboard.press('ArrowRight');
      await expect(min).toHaveValue('1.5');
      await expect(page.getByTestId('silence-suggestion')).toHaveCount(0);
      await expect(page.getByTestId('silence-note')).toHaveText('Bu anda ayarlara uyan uzun sessizlik yok.');
      await expect(page.getByTestId('silence-running')).toHaveCount(0);
      await page.getByTestId('silence-reset').click();
      await expect(page.getByTestId('silence-suggestion')).toHaveCount(1);

      // Apply → two moments, 0.9 s shorter, one undo step.
      const before = Number(await page.getByTestId('output-duration-us').textContent());
      expect(before).toBe(4.5 * S);
      await page.getByTestId('silence-apply').click();
      await expect(page.getByTestId('silence-report')).toBeVisible();
      await expect(page.getByTestId('silence-report-moments')).toHaveText('1 → 2');
      await expect(page.getByTestId('silence-report-dropped')).toHaveText('0');
      await expect(page.getByTestId('silence-report-removed')).toHaveText(/^0\.9 sn$/);
      await page.getByTestId('silence-done').click();
      await expect(dialog(page)).toHaveCount(0);
      await expect(page.getByTestId('moment-count')).toHaveText('2 an');
      const after = Number(await page.getByTestId('output-duration-us').textContent());
      expectNear(before - after, only!.endUs - only!.startUs);
      expect(before - after).toBe(only!.endUs - only!.startUs);
      const rangesText = await page.getByTestId('moment-card').locator('.moment-range').allTextContents();
      expect(rangesText).toHaveLength(2);

      await page.getByTestId('undo').click();
      await expect(page.getByTestId('moment-count')).toHaveText('1 an');
      await expect(page.getByTestId('output-duration-us')).toHaveText(String(4.5 * S));
      expect(errors).toEqual([]);
    });
  }

  test('"Dinle" plays around the cut and "Kesilmiş dinle" skips it', async ({ page }) => {
    await openWith(page, 'bursts');
    await addMoment(page, '00:00.000', '00:04.500');
    await findSilences(page);
    const row = page.getByTestId('silence-suggestion');
    const startUs = Number(await row.getAttribute('data-start-us'));
    const endUs = Number(await row.getAttribute('data-end-us'));

    // Record where the dialog's player seeks to.
    await page.evaluate(() => {
      const audio = document.querySelector<HTMLAudioElement>('[data-testid="silence-audio"]');
      const seeks: number[] = [];
      (window as unknown as { __seeks: number[] }).__seeks = seeks;
      audio?.addEventListener('seeking', () => seeks.push(audio.currentTime));
    });

    await row.getByTestId('silence-listen').click();
    await expect(row).toHaveAttribute('data-listening', 'plain');
    await expect(row.getByTestId('silence-listen')).toHaveAttribute('aria-pressed', 'true');
    // Starts 1 s before the cut, inside the moment.
    await expect
      .poll(() => page.evaluate(() => (window as unknown as { __seeks: number[] }).__seeks[0] ?? -1))
      .toBeCloseTo((startUs - S) / S, 2);
    await expect
      .poll(() =>
        page.evaluate(() => document.querySelector<HTMLAudioElement>('[data-testid="silence-audio"]')?.paused),
      )
      .toBe(false);
    // Pressing it again stops.
    await row.getByTestId('silence-listen').click();
    await expect(row).toHaveAttribute('data-listening', '');

    await page.evaluate(() => {
      (window as unknown as { __seeks: number[] }).__seeks.length = 0;
    });
    await row.getByTestId('silence-listen-cut').click();
    await expect(row).toHaveAttribute('data-listening', 'cut');
    // It jumps over the suggested range, then stops by itself after the
    // 1 s of context that follows it.
    await expect
      .poll(() => page.evaluate(() => (window as unknown as { __seeks: number[] }).__seeks.slice()), {
        timeout: 5_000,
      })
      .toEqual([expect.closeTo((startUs - S) / S, 2), expect.closeTo(endUs / S, 2)]);
    await expect(row).toHaveAttribute('data-listening', '', { timeout: 5_000 });
  });

  test('continuous noise under the tone: a note and no suggestion', async ({ page }) => {
    await openWith(page, 'lowContrast');
    await addMoment(page, '00:00.000', '00:04.500');
    await findSilences(page);
    await expect(page.getByTestId('silence-suggestion')).toHaveCount(0);
    await expect(page.getByTestId('silence-clip')).toHaveAttribute('data-status', 'low_contrast');
    await expect(page.getByTestId('silence-note')).toHaveText(
      'Bu anda sürekli ses/müzik var; güvenli bir sessizlik bulunamadı.',
    );
    await expect(page.getByTestId('silence-apply')).toBeDisabled();
    // Vazgeç leaves the recipe untouched.
    await page.getByTestId('silence-dismiss').click();
    await expect(dialog(page)).toHaveCount(0);
    await expect(page.getByTestId('moment-count')).toHaveText('1 an');
    await expect(page.getByTestId('undo')).toBeEnabled();
  });

  test('a moment shorter than the shortest silence says so', async ({ page }) => {
    await openWith(page, 'bursts');
    await addMoment(page, '00:01.000', '00:01.500');
    await findSilences(page);
    await expect(page.getByTestId('silence-clip')).toHaveAttribute('data-status', 'too_short');
    await expect(page.getByTestId('silence-note')).toHaveText(
      'Bu an, en kısa sessizlikten kısa; burada öneri yok.',
    );
  });

  test('the 20-moment limit pre-checks the longest cuts and says how many were left out', async ({ page }) => {
    await openWith(page, 'many');
    await addMoment(page, '00:00.000', '00:41.000');
    await findSilences(page);
    await expect(page.getByTestId('silence-suggestion')).toHaveCount(20);
    await expect(page.getByTestId('silence-check').and(page.locator(':checked'))).toHaveCount(19);
    await expect(page.getByTestId('silence-left-out')).toHaveText(
      '20 an sınırı: en uzun 19 kesim seçildi; 1 öneri sınır yüzünden dışarıda kaldı.',
    );
    await expect(page.getByTestId('silence-summary-moments')).toHaveText('1 → 20');

    // Checking the left-out one too would exceed the limit: said, not applied.
    await page.getByTestId('silence-check').and(page.locator(':not(:checked)')).check();
    await expect(page.getByTestId('silence-limit-exceeded')).toHaveText(
      'Seçili kesimlerle 21 an olur; en çok 20 an olabilir. Birkaç kesimi kapat.',
    );
    await expect(page.getByTestId('silence-apply')).toBeDisabled();
  });

  test('warns that result-anchored captions stay put', async ({ page }) => {
    await openWith(page, 'bursts');
    await addMoment(page, '00:00.000', '00:04.500');
    await page.getByTestId('inspector-tab-captions').click();
    await page.getByRole('tab', { name: 'Sonuç', exact: true }).click();
    await page.getByTestId('captions-add').click();
    const field = page.getByTestId('cue-draft').getByTestId('cue-text');
    await expect(field).toBeFocused();
    await page.keyboard.type('Merhaba');
    await field.blur();
    await expect(page.getByTestId('cue-draft')).toHaveCount(0);

    await findSilences(page);
    await expect(page.getByTestId('silence-captions-output')).toHaveText(
      'Sonuca bağlı altyazılar yerinde kalır; kesimden sonra kayabilir. Görüntüye bağlamak için Altyazı sekmesi.',
    );
  });

  test('a long analysis shows real progress and can be stopped', async ({ page }) => {
    test.setTimeout(120_000);
    const errors = await openWith(page, 'long');
    await addMoment(page, '00:00.000', '04:50.000');
    await expect(page.getByTestId('moment-count')).toHaveText('1 an');

    await page.getByTestId('open-silence').click();
    await expect(page.getByTestId('silence-running')).toBeVisible();
    // Progress counts seconds of audio really decoded, out of the moment's 290 s.
    await expect(page.getByTestId('silence-progress')).toHaveText(/^%\d+ · \d+\.\d \/ 290\.0 sn ses$/, {
      timeout: 15_000,
    });
    await page.getByTestId('silence-cancel').click();
    await expect(page.getByTestId('silence-running')).toHaveCount(0);
    await expect(page.getByTestId('silence-problem')).toHaveAttribute('data-reason', 'canceled');
    await expect(page.getByTestId('silence-suggestion')).toHaveCount(0);
    await expect(page.getByTestId('silence-apply')).toBeDisabled();

    // It can be restarted, and stopped again.
    await page.getByTestId('silence-retry').click();
    await expect(page.getByTestId('silence-running')).toBeVisible();
    await page.getByTestId('silence-cancel').click();
    await expect(page.getByTestId('silence-problem')).toHaveAttribute('data-reason', 'canceled');
    await page.getByTestId('silence-dismiss').click();
    await expect(page.getByTestId('moment-count')).toHaveText('1 an');
    expect(errors).toEqual([]);
  });

  /**
   * Keeps the evaluation honest: the evaluation judges cuts with ffmpeg's
   * measurement, the app decides with its own. Two moments: one from the
   * file start, one from 2.5 s (checks the decoder pre-roll mid-file).
   */
  test('parity: the browser envelope matches ffmpeg per 10 ms', async ({ page }) => {
    await page.addInitScript(() => {
      (window as unknown as { __clipSilenceEnvelopes: unknown[] }).__clipSilenceEnvelopes = [];
    });
    for (const name of ['bursts', 'noisy'] as const) {
      await openWith(page, name);
      await addMoment(page, '00:00.000', '00:04.500');
      await addMoment(page, '00:02.500', '00:04.500');
      await findSilences(page);
      const envelopes = await page.evaluate(
        () =>
          (window as unknown as { __clipSilenceEnvelopes: Array<{ startUs: number; frameUs: number; db: number[] }> })
            .__clipSilenceEnvelopes,
      );
      expect(envelopes.map((item) => [item.startUs, item.frameUs, item.db.length])).toEqual([
        [0, 10_000, 450],
        [2.5 * S, 10_000, 200],
      ]);

      const reference = ffmpegEnvelope(silenceFixture(name).file);
      expect(reference.length).toBeGreaterThanOrEqual(450);
      let loud = 0;
      let quiet = 0;
      let maxDiff = 0;
      for (const envelope of envelopes) {
        const offset = Math.round(envelope.startUs / envelope.frameUs);
        envelope.db.forEach((ours, index) => {
          const theirs = reference[offset + index]!;
          const where = `${name} frame ${offset + index}: ffmpeg ${theirs}, browser ${ours}`;
          if (theirs <= -90) {
            quiet += 1;
            expect(ours, where).toBeLessThanOrEqual(-90);
          } else {
            loud += 1;
            const diff = Math.abs(ours - theirs);
            maxDiff = Math.max(maxDiff, diff);
            expect(diff, where).toBeLessThanOrEqual(1);
          }
        });
      }
      const line = `${name}: ${loud + quiet} frames, ${loud} non-silent (max |Δ| ${maxDiff.toFixed(4)} dB), ${quiet} silent (both ≤ −90 dBFS)`;
      console.log(`[parity] ${line}`);
      test.info().annotations.push({ type: 'parity', description: line });
      await page.evaluate(() => {
        (window as unknown as { __clipSilenceEnvelopes: unknown[] }).__clipSilenceEnvelopes.length = 0;
      });
    }
  });
});

test.describe('silence suggestions on a phone', () => {
  test.use({ viewport: { width: 390, height: 844 } });

  test('opens from the moments sheet, fits 390 px, applies', async ({ page }) => {
    await openWith(page, 'bursts');
    await addMoment(page, '00:00.000', '00:04.500');
    await page.getByTestId('tab-moments').click();
    await page.getByTestId('open-silence').click();
    await expect(dialog(page)).toBeVisible();
    await expect(page.getByTestId('silence-running')).toHaveCount(0, { timeout: 30_000 });
    await expect(page.getByTestId('silence-suggestion')).toHaveCount(1);

    const overflow = await page.evaluate(() => {
      const panel = document.querySelector<HTMLElement>('.dialog-wide');
      return {
        page: document.documentElement.scrollWidth - window.innerWidth,
        dialog: panel ? panel.scrollWidth - panel.clientWidth : -1,
        dialogRight: panel ? panel.getBoundingClientRect().right : -1,
      };
    });
    expect(overflow.page).toBeLessThanOrEqual(0);
    expect(overflow.dialog).toBe(0);
    expect(overflow.dialogRight).toBeLessThanOrEqual(390);

    // Keyboard: the checkbox, the listen buttons and Apply are reachable.
    const check = page.getByTestId('silence-check');
    await check.focus();
    await page.keyboard.press('Space');
    await expect(check).not.toBeChecked();
    await page.keyboard.press('Space');
    await expect(check).toBeChecked();

    await page.getByTestId('silence-apply').click();
    await expect(page.getByTestId('silence-report')).toBeVisible();
    // Apply leaves with the list; focus goes to the report, not the page behind.
    await expect(page.locator('#silence-report-title')).toBeFocused();
    await page.getByTestId('silence-done').click();
    await expect(dialog(page)).toHaveCount(0);
  });
});

/**
 * Screenshots for review (synthetic media only). Opt-in, so a normal test run
 * does not rewrite the committed images: SILENCE_SHOTS=1.
 */
test.describe('silence screenshots', () => {
  test.skip(!process.env.SILENCE_SHOTS, 'set SILENCE_SHOTS=1 to refresh the screenshots');

  for (const [label, viewport] of [
    ['desktop', { width: 1440, height: 900 }],
    ['phone', { width: 390, height: 844 }],
  ] as const) {
    test(`dialog with suggestions (${label})`, async ({ page }) => {
      await page.setViewportSize(viewport);
      await openWith(page, 'showcase');
      await addMoment(page, '00:00.000', '00:06.000');
      await addMoment(page, '00:06.000', '00:12.000');
      if (label === 'phone') await page.getByTestId('tab-moments').click();
      await findSilences(page);
      await expect(page.getByTestId('silence-suggestion').first()).toBeVisible();
      // On a phone the settings fill the first screen; show the list instead.
      if (label === 'phone') {
        await page.getByText('Öneriler', { exact: true }).evaluate((node) => node.scrollIntoView({ block: 'start' }));
      }
      mkdirSync(SHOTS, { recursive: true });
      await page.screenshot({ path: join(SHOTS, `silence-dialog-${label}.png`) });
    });
  }
});
